"""Fixed THN private coordinates; no clients, handlers or authoring methods."""
PRIVATE_PREFIX = "private/test/thehairnarrative.com/thehairnarrative-com-journal/"
PARTITION_PREFIX = "THN#test#thehairnarrative.com#journal-owner#thehairnarrative-com#thehairnarrative-com-journal#"
ARTICLE_PK = PARTITION_PREFIX + "ARTICLES"
METADATA_TABLE = "zoolanding-content-hub-test-ThnContentHubV2Metadata"
AUDIT_TABLE = "zoolanding-content-hub-test-ThnContentHubV2Audit"
